# Machine learning : Regression - Project 1

## importing libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## importing the dataset

In [41]:
dataset = pd.read_csv('/Users/namanmp/ml_projects/Student_Performance.csv')
X = dataset.iloc[:, :4].values
y = dataset.iloc[:, -1].values.reshape(-1,1)

In [42]:
print(X)

[[7 99 'Yes' 9]
 [4 82 'No' 4]
 [8 51 'Yes' 7]
 ...
 [6 83 'Yes' 8]
 [9 97 'Yes' 7]
 [7 74 'No' 8]]


In [44]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [2])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
X

array([[0.0, 1.0, 7, 99, 9],
       [1.0, 0.0, 4, 82, 4],
       [0.0, 1.0, 8, 51, 7],
       ...,
       [0.0, 1.0, 6, 83, 8],
       [0.0, 1.0, 9, 97, 7],
       [1.0, 0.0, 7, 74, 8]], shape=(10000, 5), dtype=object)

In [45]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X)
X = imputer.transform(X)

In [4]:
print(y)

[91. 65. 45. ... 74. 95. 64.]


## dividing between training and testing set

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

## training machine learning models

### Multiple linear regression

In [15]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X_train , y_train)


array([[50.46443613],
       [53.10077726],
       [78.27207629],
       ...,
       [61.92684246],
       [39.15895897],
       [89.59303935]], shape=(3000, 1))

In [20]:
y_pred = lin_reg.predict(X_test)

In [21]:
y_pred = lin_reg.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[50.46 53.  ]
 [53.1  50.  ]
 [78.27 80.  ]
 ...
 [61.93 62.  ]
 [39.16 39.  ]
 [89.59 88.  ]]


In [ ]:
from sklearn.metrics import r2_score
multiple_lin_reg_score = r2_score(y_test, y_pred)

0.9888065859708454